Fixed ONDD init script
Signed-off-by: Branko Vukelic <branko@outernet.is>

diff --git a/rpi/rootfs_overlay/etc/init.d/S90ondd b/rpi/rootfs_overlay/etc/init.d/S90ondd
--- a/rpi/rootfs_overlay/etc/init.d/S90ondd
+++ b/rpi/rootfs_overlay/etc/init.d/S90ondd
@@ -1,43 +1,49 @@
 #!/bin/sh
 
-DAEMON=/usr/sbin/ondd
-ONDD_PID=/var/run/ondd.pid
-ONDD_OUT=/mnt/data/downloads
-FRONTEND=/dev/dvb/adapter0/frontend0
+PID_FILE=/var/run/ondd.pid
+CACHE_PATH=/mnt/data/cache
+OUTPUT_PATH=/mnt/data/downloads
+
+start() {
+  [ -d /mnt/data/ondd ] || mkdir /mnt/data/ondd
+  [ -d $CACHE_PATH ] || mkdir $CACHE_PATH
+  [ -d $OUTPUT_PATH ] || mkdir $OUTPUT_PATH
+
+  echo -n "Starting ondd: "
+  start-stop-daemon -S -q -p $PID_FILE --exec /usr/sbin/ondd -- -d --pid-file $PID_FILE -c $CACHE_PATH -o $OUTPUT_PATH
+  if [ $? ]; then
+    echo "OK"
+  else
+    echo "FAILED"
+  fi
+}
+
+stop() {
+  echo -n "Stopping ondd: "
+  start-stop-daemon -K -q -p $PID_FILE
+  [ -f $PID_FILE ] && rm $PID_FILE
+  echo "OK"
+}
+
+restart() {
+  stop
+  /bin/sleep 1
+  start
+}
 
 case "$1" in
-    start)
-        [ -f $ONDD_PID ] && exit 0
-        echo -n "Starting ondd: "
-        if [ ! -c $FRONTEND ]
-        then
-            echo "FAIL"
-            exit 0
-        fi
-        start-stop-daemon -S -q -p $ONDD_PID -x $DAEMON \
-            -- -d --pid-file $ONDD_PID -o $ONDD_OUT
-        if [ $? = 0 ]
-        then
-            echo "OK"
-        else
-            [ -f $ONDD_PID ] && rm $ONDD_PID
-            echo "FAIL"
-        fi
-        ;;
-    stop)
-        echo -n "Stopping ondd: "
-        start-stop-daemon -K -q -p $ONDD_PID
-        [ -f $ONDD_PID ] && rm $ONDD_PID
-        [ $? = 0 ] && echo "OK" || echo "FAIL"
-        ;;
-    restart|reload)
-        $0 stop
-        /bin/sleep 1
-        $0 start
-        ;;
-    *)
-        echo "Usage: $0 {start|stop|restart}"
-        exit 1
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  restart|reload)
+    restart
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|reload}"
+    exit 1
 esac
 
-exit 0
+exit $?
